In [1]:
# import numpy 
import numpy as np 

In [2]:
# 1D array of length 3 with all values 0 
Z1 = np.zeros(3)
print(Z1)

[0. 0. 0.]


In [3]:
# 2D array of 3x4 with all values 0 
Z2 = np.zeros((3,4))
print(Z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# 1D array of length 3 with all values 1
A1 = np.ones(3)  
print(A1) 

[1. 1. 1.]


In [5]:
# 2D array of 3x4 with all values 1
A2 = np.ones((3,4))
A2
print(A2) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# not specify start and step 
A1 = np.arange(10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# specifying start and step 
A2 = np.arange(start=1, stop=10, step=2)
print(A2)

[1 3 5 7 9]


In [8]:
# another way 
A3 = np.arange(10, 25, 2)
print(A3)

[10 12 14 16 18 20 22 24]


In [9]:
# array of evenly spaced values 0 to 2, here sample size = 9
L1 = np.linspace(0,2,9)
print(L1)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [10]:
# Array of 6 evenly divided values from 0 to 100
L2 = np.linspace(0, 100, 6)
print(L2) 

[  0.  20.  40.  60.  80. 100.]


In [11]:
# Array of 1 to 5
L3 = np.linspace(start=1, stop=5, endpoint=True, retstep=False)
print(L3) 

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [12]:
# Array of 1 to 5
L4 = np.linspace(start=1, stop=5, endpoint=True, retstep=True)
print(L4) 

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]), 0.08163265306122448)


In [13]:
# generate an array with 5 samples with base 10.0 
np.logspace(1, 10, num=5, endpoint=True)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [14]:
# generate an array with 5 samples with base 2.0
np.logspace(1, 10, num=5, endpoint=True, base=2.0)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [15]:
# generate 2x2 constant array, constant = 7
C = np.full((2, 2), 7)
print(C)

[[7 7]
 [7 7]]


In [16]:
# generate 2x2 identity matrix 
I = np.eye(2)
print(I) 

[[1. 0.]
 [0. 1.]]


In [17]:
# create an array with randomly generated 5 values 
R = np.random.rand(5)
print(R)

[0.08115396 0.91530316 0.26206871 0.05754532 0.67980871]


In [18]:
# generate 2x2 array of random values 
R1 = np.random.random((2, 2))
print(R1)

[[0.94519465 0.94042736]
 [0.32263687 0.8434665 ]]


In [19]:
# generate 4x5 array of random floats between 0-1
R2 = np.random.rand(4,5)
print(R2)

[[0.75618687 0.81066574 0.36406258 0.16053091 0.3279457 ]
 [0.47103502 0.38129048 0.43118472 0.67151511 0.17040015]
 [0.14898565 0.31155506 0.86004939 0.01953252 0.58128641]
 [0.47164394 0.73766643 0.08602257 0.95746435 0.87624401]]


In [20]:
# generate 6x7 array of random floats between 0-100
R3 = np.random.rand(6,7)*100
print(R3)

[[52.59519672 69.0510672  23.50194952 97.47709181 99.5330252  15.34740319
  34.03033328]
 [97.50807544 96.85626376 18.28677787 87.7248113  36.02458891 73.58972577
  45.24166565]
 [12.01287356 16.65247859 48.55173756 57.90112051  7.52725359 99.48922131
  32.24834159]
 [42.90533204 98.56489819 31.85846737 47.1346735  38.91416562 57.29670327
  50.61362612]
 [79.40405334  5.28783143 16.9375285  99.39368158 57.56517753 95.28917609
  33.97058092]
 [71.45373255 67.30141221 73.86169974 65.04032469 23.87017182  0.27369161
  14.99841722]]


In [21]:
# generate 2x3 array of random ints between 0-4
R4 = np.random.randint(5, size=(2,3))
print(R4)

[[3 2 2]
 [3 0 1]]


In [22]:
# generate an empty array 
E1 = np.empty(2) 
print(E1)

[9.9e-324 1.5e-323]


In [23]:
# 2x2 empty array
E2 = np.empty((2, 2)) 
print(E2)

[[0.94519465 0.94042736]
 [0.32263687 0.8434665 ]]


In [24]:
# generate an array of floats 
D = np.ones((2, 3, 4), dtype=np.float16)
D

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)