# Copying / Sorting / Reshaping

In [1]:
import numpy as np

## Copy: Copies array to new memory


In [2]:
A1 = np.arange(10)
A2 = np.copy(A1)
A2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## View: Creates view of array elements with type(dtype)


In [5]:
A3 = A2.view(np.float16)
A3

array([0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 6.0e-08, 0.0e+00, 0.0e+00,
       0.0e+00, 1.2e-07, 0.0e+00, 0.0e+00, 0.0e+00, 1.8e-07, 0.0e+00,
       0.0e+00, 0.0e+00, 2.4e-07, 0.0e+00, 0.0e+00, 0.0e+00, 3.0e-07,
       0.0e+00, 0.0e+00, 0.0e+00, 3.6e-07, 0.0e+00, 0.0e+00, 0.0e+00,
       4.2e-07, 0.0e+00, 0.0e+00, 0.0e+00, 4.8e-07, 0.0e+00, 0.0e+00,
       0.0e+00, 5.4e-07, 0.0e+00, 0.0e+00, 0.0e+00], dtype=float16)

## Sort-1: Sorts array(Element-Wise)


In [6]:
# Unsorted array
A4 = np.array([9, 2, 3,1, 5, 10])
A4

array([ 9,  2,  3,  1,  5, 10])

In [10]:
# Call sort function
A4.sort()

In [11]:
# Sorted array
A4

array([ 1,  2,  3,  5,  9, 10])

## Sort-2: Sorts specific axis of array
![Axis](./figs/axis.png)

In [12]:
# Row and column unsorted
A5 = np.array([[4, 1, 3], [9, 5, 8]])
A5

array([[4, 1, 3],
       [9, 5, 8]])

In [13]:
# Apply sort function on specific axis=0 
A5.sort(axis=0)

In [14]:
# Sorted array--> axis=0
A5

array([[4, 1, 3],
       [9, 5, 8]])

In [16]:
# Apply sort function on specific axis = 1
A5.sort(axis=1)

In [17]:
# Sorted array--> axis=1
A5

array([[1, 3, 4],
       [5, 8, 9]])

## Flatten: Flattens 2D array to 1D array


In [19]:
# 2D array
A6 = np.array([[4, 1, 3], [9, 5, 8]])
# 1D array 
A6.flatten()

array([4, 1, 3, 9, 5, 8])

## Transpose: Transposes array (rows become columns and vice versa)


In [22]:
A7 = np.array([[4, 1, 3], [9, 5, 8]])
A7

array([[4, 1, 3],
       [9, 5, 8]])

In [21]:
# Transpose A7 
A7.T

array([[4, 9],
       [1, 5],
       [3, 8]])

## Reshape: Reshapes arr to `r` rows, `c` columns without changing data
![Reshape](./figs/reshape.png)

In [31]:
A8 = np.array([(8,9,10),(11,12,13)])
A8

array([[ 8,  9, 10],
       [11, 12, 13]])

In [32]:
# Reshape --> 3x4
A8.reshape(3,2)

array([[ 8,  9],
       [10, 11],
       [12, 13]])

## Resize:  Changes arr shape to `rxc` and fills new values with 0


In [33]:
A9 = np.array([(8,9,10),(11,12,13)])
A9

array([[ 8,  9, 10],
       [11, 12, 13]])

In [37]:
# Resize 
A9.resize(3, 2)
A9

array([[ 8,  9],
       [10, 11],
       [12, 13]])