## Vectors 
- A vector has magnitude (size) and direction
- Use NumPy to create a one-dimensional array 
- Vector can be created as row or column using NumPy 
![vectors](../img/vector-mag-dir.svg)

__See More__
* https://www.mathsisfun.com/algebra/vectors.html
* https://en.wikipedia.org/wiki/Euclidean_vector

In [1]:
# Load NumPy Library 
import numpy as np 

In [3]:
# Create a vector as row 
vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [5]:
# Create a vector as column 
vector_column = np.array([[1], [2], [3]]) 
vector_column

array([[1],
       [2],
       [3]])

## Matrix 
- In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns
- Use NumPy to create a two-dimensional array

![matrix](../img/Matris.png)

## Matrix Order
- You can think of an $r x c$ matrix as a set of r row vectors, each having c elements; or you can think of it as a set of c column vectors, each having r elements.
- The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix or (b) the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.
- If r is less than c, then the maximum rank of the matrix is r.
- If r is greater than c, then the maximum rank of the matrix is c.
![matrix](../img/Matrix_1000.gif)

__See More__
* https://en.wikipedia.org/wiki/Matrix_(mathematics)
* https://mathworld.wolfram.com/Matrix.html
* https://stattrek.com/matrix-algebra/matrix-rank.aspx

In [6]:
# Create a matrix in NumPy 
mat = np.array([[1, 2], [3,4], [4, 6]])
mat 

array([[1, 2],
       [3, 4],
       [4, 6]])

In [10]:
# Check dimension of matrix 
mat.ndim

2